# Your project's server will run on localhost:xxxx at this port
PORT: 8000
# Gulp will reference these paths when it copies files
PATHS:
  # Path to tmp to build the translations
  tmp: "tmp"
  # Path to dist folder
  dist: "dist"
  # Path to fonts folder
  fonts: "src/assets/fonts"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "node_modules/bootstrap/scss"
  # Paths to JavaScript entry points for webpack to bundle modules
  entries:
    - "src/assets/js/app.js"


